# Database: postgres
version: "3.1"

services:

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: swe304
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "MyNewPass1!"
    ports:
      - "5432:5432"
    networks:
      - sbnet

  devops-gradle:
    image: travula00/devops:latest
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/swe304
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "MyNewPass1!"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_OPEN_IN_VIEW: false
    volumes:
          - /absolute/path/to/src/main/resources/static/images:/src/main/resources/static/images
    networks:
      - sbnet

volumes:
  postgres_data:
    external: true

networks:
  sbnet:
    external: true
