# This file is used to configure the application properties.
spring:
  application:
    name: devops-gradle
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/swe304"
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:MyNewPass1!}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false

aws:
  bucket:
    name: ${AWS_BUCKET_NAME:devops-gradle}
  accessKey: ${AWS_ACCESS_KEY_ID:QWERQWERQWERQWREQWER}
  secretKey: ${AWS_SECRET_ACCESS_KEY:QWERQWERQWERQWREQWERQWERQWERQWERQWERQWER}

server:
  port: ${PORT:3000}